/**
 * WordPress dependencies
 */
import { _x } from '@safe-wordpress/i18n';

/**
 * Internal dependencies
 */
import { sortObjectKeysUsingValue } from './functions';

export const worldCountries: Record< string, string > =
	sortObjectKeysUsingValue( {
		AF: _x( 'Afghanistan', 'text', 'nelio-session-recordings' ),
		AX: _x( 'Åland Islands', 'text', 'nelio-session-recordings' ),
		AL: _x( 'Albania', 'text', 'nelio-session-recordings' ),
		DZ: _x( 'Algeria', 'text', 'nelio-session-recordings' ),
		AS: _x( 'American Samoa', 'text', 'nelio-session-recordings' ),
		AD: _x( 'Andorra', 'text', 'nelio-session-recordings' ),
		AO: _x( 'Angola', 'text', 'nelio-session-recordings' ),
		AI: _x( 'Anguilla', 'text', 'nelio-session-recordings' ),
		AQ: _x( 'Antarctica', 'text', 'nelio-session-recordings' ),
		AG: _x( 'Antigua and Barbuda', 'text', 'nelio-session-recordings' ),
		AR: _x( 'Argentina', 'text', 'nelio-session-recordings' ),
		AM: _x( 'Armenia', 'text', 'nelio-session-recordings' ),
		AW: _x( 'Aruba', 'text', 'nelio-session-recordings' ),
		AU: _x( 'Australia', 'text', 'nelio-session-recordings' ),
		AT: _x( 'Austria', 'text', 'nelio-session-recordings' ),
		AZ: _x( 'Azerbaijan', 'text', 'nelio-session-recordings' ),
		BS: _x( 'Bahamas', 'text', 'nelio-session-recordings' ),
		BH: _x( 'Bahrain', 'text', 'nelio-session-recordings' ),
		BD: _x( 'Bangladesh', 'text', 'nelio-session-recordings' ),
		BB: _x( 'Barbados', 'text', 'nelio-session-recordings' ),
		BY: _x( 'Belarus', 'text', 'nelio-session-recordings' ),
		BE: _x( 'Belgium', 'text', 'nelio-session-recordings' ),
		BZ: _x( 'Belize', 'text', 'nelio-session-recordings' ),
		BJ: _x( 'Benin', 'text', 'nelio-session-recordings' ),
		BM: _x( 'Bermuda', 'text', 'nelio-session-recordings' ),
		BT: _x( 'Bhutan', 'text', 'nelio-session-recordings' ),
		BO: _x( 'Bolivia', 'text', 'nelio-session-recordings' ),
		BQ: _x(
			'Bonaire, Sint Eustatius and Saba',
			'text',
			'nelio-session-recordings'
		),
		BA: _x( 'Bosnia and Herzegovina', 'text', 'nelio-session-recordings' ),
		BW: _x( 'Botswana', 'text', 'nelio-session-recordings' ),
		BV: _x( 'Bouvet Island', 'text', 'nelio-session-recordings' ),
		BR: _x( 'Brazil', 'text', 'nelio-session-recordings' ),
		IO: _x(
			'British Indian Ocean Territory',
			'text',
			'nelio-session-recordings'
		),
		BN: _x( 'Brunei Darussalam', 'text', 'nelio-session-recordings' ),
		BG: _x( 'Bulgaria', 'text', 'nelio-session-recordings' ),
		BF: _x( 'Burkina Faso', 'text', 'nelio-session-recordings' ),
		BI: _x( 'Burundi', 'text', 'nelio-session-recordings' ),
		KH: _x( 'Cambodia', 'text', 'nelio-session-recordings' ),
		CM: _x( 'Cameroon', 'text', 'nelio-session-recordings' ),
		CA: _x( 'Canada', 'text', 'nelio-session-recordings' ),
		CV: _x( 'Cape Verde', 'text', 'nelio-session-recordings' ),
		KY: _x( 'Cayman Islands', 'text', 'nelio-session-recordings' ),
		CF: _x(
			'Central African Republic',
			'text',
			'nelio-session-recordings'
		),
		TD: _x( 'Chad', 'text', 'nelio-session-recordings' ),
		CL: _x( 'Chile', 'text', 'nelio-session-recordings' ),
		CN: _x( 'China', 'text', 'nelio-session-recordings' ),
		CX: _x( 'Christmas Island', 'text', 'nelio-session-recordings' ),
		CC: _x( 'Cocos (Keeling) Islands', 'text', 'nelio-session-recordings' ),
		CO: _x( 'Colombia', 'text', 'nelio-session-recordings' ),
		KM: _x( 'Comoros', 'text', 'nelio-session-recordings' ),
		CG: _x( 'Congo', 'text', 'nelio-session-recordings' ),
		CD: _x(
			'Congo, the Democratic Republic of the',
			'text',
			'nelio-session-recordings'
		),
		CK: _x( 'Cook Islands', 'text', 'nelio-session-recordings' ),
		CR: _x( 'Costa Rica', 'text', 'nelio-session-recordings' ),
		CI: _x( 'Côte d’Ivoire', 'text', 'nelio-session-recordings' ),
		HR: _x( 'Croatia', 'text', 'nelio-session-recordings' ),
		CU: _x( 'Cuba', 'text', 'nelio-session-recordings' ),
		CW: _x( 'Curaçao', 'text', 'nelio-session-recordings' ),
		CY: _x( 'Cyprus', 'text', 'nelio-session-recordings' ),
		CZ: _x( 'Czech Republic', 'text', 'nelio-session-recordings' ),
		DK: _x( 'Denmark', 'text', 'nelio-session-recordings' ),
		DJ: _x( 'Djibouti', 'text', 'nelio-session-recordings' ),
		DM: _x( 'Dominica', 'text', 'nelio-session-recordings' ),
		DO: _x( 'Dominican Republic', 'text', 'nelio-session-recordings' ),
		EC: _x( 'Ecuador', 'text', 'nelio-session-recordings' ),
		EG: _x( 'Egypt', 'text', 'nelio-session-recordings' ),
		SV: _x( 'El Salvador', 'text', 'nelio-session-recordings' ),
		GQ: _x( 'Equatorial Guinea', 'text', 'nelio-session-recordings' ),
		ER: _x( 'Eritrea', 'text', 'nelio-session-recordings' ),
		EE: _x( 'Estonia', 'text', 'nelio-session-recordings' ),
		SZ: _x( 'Eswatini', 'text', 'nelio-session-recordings' ),
		ET: _x( 'Ethiopia', 'text', 'nelio-session-recordings' ),
		FK: _x(
			'Falkland Islands (Malvinas)',
			'text',
			'nelio-session-recordings'
		),
		FO: _x( 'Faroe Islands', 'text', 'nelio-session-recordings' ),
		FJ: _x( 'Fiji', 'text', 'nelio-session-recordings' ),
		FI: _x( 'Finland', 'text', 'nelio-session-recordings' ),
		FR: _x( 'France', 'text', 'nelio-session-recordings' ),
		GF: _x( 'French Guiana', 'text', 'nelio-session-recordings' ),
		PF: _x( 'French Polynesia', 'text', 'nelio-session-recordings' ),
		TF: _x(
			'French Southern Territories',
			'text',
			'nelio-session-recordings'
		),
		GA: _x( 'Gabon', 'text', 'nelio-session-recordings' ),
		GM: _x( 'Gambia', 'text', 'nelio-session-recordings' ),
		GE: _x( 'Georgia', 'text', 'nelio-session-recordings' ),
		DE: _x( 'Germany', 'text', 'nelio-session-recordings' ),
		GH: _x( 'Ghana', 'text', 'nelio-session-recordings' ),
		GI: _x( 'Gibraltar', 'text', 'nelio-session-recordings' ),
		GR: _x( 'Greece', 'text', 'nelio-session-recordings' ),
		GL: _x( 'Greenland', 'text', 'nelio-session-recordings' ),
		GD: _x( 'Grenada', 'text', 'nelio-session-recordings' ),
		GP: _x( 'Guadeloupe', 'text', 'nelio-session-recordings' ),
		GU: _x( 'Guam', 'text', 'nelio-session-recordings' ),
		GT: _x( 'Guatemala', 'text', 'nelio-session-recordings' ),
		GG: _x( 'Guernsey', 'text', 'nelio-session-recordings' ),
		GN: _x( 'Guinea', 'text', 'nelio-session-recordings' ),
		GW: _x( 'Guinea-Bissau', 'text', 'nelio-session-recordings' ),
		GY: _x( 'Guyana', 'text', 'nelio-session-recordings' ),
		HT: _x( 'Haiti', 'text', 'nelio-session-recordings' ),
		HM: _x(
			'Heard Island and Mcdonald Islands',
			'text',
			'nelio-session-recordings'
		),
		VA: _x(
			'Holy See (Vatican City State)',
			'text',
			'nelio-session-recordings'
		),
		HN: _x( 'Honduras', 'text', 'nelio-session-recordings' ),
		HK: _x( 'Hong Kong', 'text', 'nelio-session-recordings' ),
		HU: _x( 'Hungary', 'text', 'nelio-session-recordings' ),
		IS: _x( 'Iceland', 'text', 'nelio-session-recordings' ),
		IN: _x( 'India', 'text', 'nelio-session-recordings' ),
		ID: _x( 'Indonesia', 'text', 'nelio-session-recordings' ),
		IR: _x(
			'Iran, Islamic Republic of',
			'text',
			'nelio-session-recordings'
		),
		IQ: _x( 'Iraq', 'text', 'nelio-session-recordings' ),
		IE: _x( 'Ireland', 'text', 'nelio-session-recordings' ),
		IM: _x( 'Isle of Man', 'text', 'nelio-session-recordings' ),
		IL: _x( 'Israel', 'text', 'nelio-session-recordings' ),
		IT: _x( 'Italy', 'text', 'nelio-session-recordings' ),
		JM: _x( 'Jamaica', 'text', 'nelio-session-recordings' ),
		JP: _x( 'Japan', 'text', 'nelio-session-recordings' ),
		JE: _x( 'Jersey', 'text', 'nelio-session-recordings' ),
		JO: _x( 'Jordan', 'text', 'nelio-session-recordings' ),
		KZ: _x( 'Kazakhstan', 'text', 'nelio-session-recordings' ),
		KE: _x( 'Kenya', 'text', 'nelio-session-recordings' ),
		KI: _x( 'Kiribati', 'text', 'nelio-session-recordings' ),
		XK: _x( 'Kosovo', 'text', 'nelio-session-recordings' ),
		KP: _x( 'North Korea', 'text', 'nelio-session-recordings' ),
		KR: _x( 'South Korea', 'text', 'nelio-session-recordings' ),
		KW: _x( 'Kuwait', 'text', 'nelio-session-recordings' ),
		KG: _x( 'Kyrgyzstan', 'text', 'nelio-session-recordings' ),
		LA: _x(
			'Lao People’s Democratic Republic',
			'text',
			'nelio-session-recordings'
		),
		LV: _x( 'Latvia', 'text', 'nelio-session-recordings' ),
		LB: _x( 'Lebanon', 'text', 'nelio-session-recordings' ),
		LS: _x( 'Lesotho', 'text', 'nelio-session-recordings' ),
		LR: _x( 'Liberia', 'text', 'nelio-session-recordings' ),
		LY: _x( 'Libya', 'text', 'nelio-session-recordings' ),
		LI: _x( 'Liechtenstein', 'text', 'nelio-session-recordings' ),
		LT: _x( 'Lithuania', 'text', 'nelio-session-recordings' ),
		LU: _x( 'Luxembourg', 'text', 'nelio-session-recordings' ),
		MO: _x( 'Macao', 'text', 'nelio-session-recordings' ),
		MG: _x( 'Madagascar', 'text', 'nelio-session-recordings' ),
		MW: _x( 'Malawi', 'text', 'nelio-session-recordings' ),
		MY: _x( 'Malaysia', 'text', 'nelio-session-recordings' ),
		MV: _x( 'Maldives', 'text', 'nelio-session-recordings' ),
		ML: _x( 'Mali', 'text', 'nelio-session-recordings' ),
		MT: _x( 'Malta', 'text', 'nelio-session-recordings' ),
		MH: _x( 'Marshall Islands', 'text', 'nelio-session-recordings' ),
		MQ: _x( 'Martinique', 'text', 'nelio-session-recordings' ),
		MR: _x( 'Mauritania', 'text', 'nelio-session-recordings' ),
		MU: _x( 'Mauritius', 'text', 'nelio-session-recordings' ),
		YT: _x( 'Mayotte', 'text', 'nelio-session-recordings' ),
		MX: _x( 'Mexico', 'text', 'nelio-session-recordings' ),
		FM: _x(
			'Micronesia, Federated States of',
			'text',
			'nelio-session-recordings'
		),
		MD: _x( 'Moldova, Republic of', 'text', 'nelio-session-recordings' ),
		MC: _x( 'Monaco', 'text', 'nelio-session-recordings' ),
		MN: _x( 'Mongolia', 'text', 'nelio-session-recordings' ),
		ME: _x( 'Montenegro', 'text', 'nelio-session-recordings' ),
		MS: _x( 'Montserrat', 'text', 'nelio-session-recordings' ),
		MA: _x( 'Morocco', 'text', 'nelio-session-recordings' ),
		MZ: _x( 'Mozambique', 'text', 'nelio-session-recordings' ),
		MM: _x( 'Myanmar', 'text', 'nelio-session-recordings' ),
		NA: _x( 'Namibia', 'text', 'nelio-session-recordings' ),
		NR: _x( 'Nauru', 'text', 'nelio-session-recordings' ),
		NP: _x( 'Nepal', 'text', 'nelio-session-recordings' ),
		NL: _x( 'Netherlands', 'text', 'nelio-session-recordings' ),
		NC: _x( 'New Caledonia', 'text', 'nelio-session-recordings' ),
		NZ: _x( 'New Zealand', 'text', 'nelio-session-recordings' ),
		NI: _x( 'Nicaragua', 'text', 'nelio-session-recordings' ),
		NE: _x( 'Niger', 'text', 'nelio-session-recordings' ),
		NG: _x( 'Nigeria', 'text', 'nelio-session-recordings' ),
		NU: _x( 'Niue', 'text', 'nelio-session-recordings' ),
		NF: _x( 'Norfolk Island', 'text', 'nelio-session-recordings' ),
		MK: _x(
			'North Macedonia, Republic of',
			'text',
			'nelio-session-recordings'
		),
		MP: _x(
			'Northern Mariana Islands',
			'text',
			'nelio-session-recordings'
		),
		NO: _x( 'Norway', 'text', 'nelio-session-recordings' ),
		OM: _x( 'Oman', 'text', 'nelio-session-recordings' ),
		PK: _x( 'Pakistan', 'text', 'nelio-session-recordings' ),
		PW: _x( 'Palau', 'text', 'nelio-session-recordings' ),
		PS: _x(
			'Palestinian Territory, Occupied',
			'text',
			'nelio-session-recordings'
		),
		PA: _x( 'Panama', 'text', 'nelio-session-recordings' ),
		PG: _x( 'Papua New Guinea', 'text', 'nelio-session-recordings' ),
		PY: _x( 'Paraguay', 'text', 'nelio-session-recordings' ),
		PE: _x( 'Peru', 'text', 'nelio-session-recordings' ),
		PH: _x( 'Philippines', 'text', 'nelio-session-recordings' ),
		PN: _x( 'Pitcairn', 'text', 'nelio-session-recordings' ),
		PL: _x( 'Poland', 'text', 'nelio-session-recordings' ),
		PT: _x( 'Portugal', 'text', 'nelio-session-recordings' ),
		PR: _x( 'Puerto Rico', 'text', 'nelio-session-recordings' ),
		QA: _x( 'Qatar', 'text', 'nelio-session-recordings' ),
		RE: _x( 'Reunion', 'text', 'nelio-session-recordings' ),
		RO: _x( 'Romania', 'text', 'nelio-session-recordings' ),
		RU: _x( 'Russian Federation', 'text', 'nelio-session-recordings' ),
		RW: _x( 'Rwanda', 'text', 'nelio-session-recordings' ),
		BL: _x( 'Saint Barthélemy', 'text', 'nelio-session-recordings' ),
		SH: _x( 'Saint Helena', 'text', 'nelio-session-recordings' ),
		KN: _x( 'Saint Kitts and Nevis', 'text', 'nelio-session-recordings' ),
		LC: _x( 'Saint Lucia', 'text', 'nelio-session-recordings' ),
		MF: _x(
			'Saint Martin (French part)',
			'text',
			'nelio-session-recordings'
		),
		PM: _x(
			'Saint Pierre and Miquelon',
			'text',
			'nelio-session-recordings'
		),
		VC: _x(
			'Saint Vincent and the Grenadines',
			'text',
			'nelio-session-recordings'
		),
		WS: _x( 'Samoa', 'text', 'nelio-session-recordings' ),
		SM: _x( 'San Marino', 'text', 'nelio-session-recordings' ),
		ST: _x( 'Sao Tome and Principe', 'text', 'nelio-session-recordings' ),
		SA: _x( 'Saudi Arabia', 'text', 'nelio-session-recordings' ),
		SN: _x( 'Senegal', 'text', 'nelio-session-recordings' ),
		RS: _x( 'Serbia', 'text', 'nelio-session-recordings' ),
		SC: _x( 'Seychelles', 'text', 'nelio-session-recordings' ),
		SL: _x( 'Sierra Leone', 'text', 'nelio-session-recordings' ),
		SG: _x( 'Singapore', 'text', 'nelio-session-recordings' ),
		SX: _x(
			'Sint Maarten (Dutch part)',
			'text',
			'nelio-session-recordings'
		),
		SK: _x( 'Slovakia', 'text', 'nelio-session-recordings' ),
		SI: _x( 'Slovenia', 'text', 'nelio-session-recordings' ),
		SB: _x( 'Solomon Islands', 'text', 'nelio-session-recordings' ),
		SO: _x( 'Somalia', 'text', 'nelio-session-recordings' ),
		ZA: _x( 'South Africa', 'text', 'nelio-session-recordings' ),
		GS: _x(
			'South Georgia and the South Sandwich Islands',
			'text',
			'nelio-session-recordings'
		),
		SS: _x( 'South Sudan', 'text', 'nelio-session-recordings' ),
		ES: _x( 'Spain', 'text', 'nelio-session-recordings' ),
		LK: _x( 'Sri Lanka', 'text', 'nelio-session-recordings' ),
		SD: _x( 'Sudan', 'text', 'nelio-session-recordings' ),
		SR: _x( 'Suriname', 'text', 'nelio-session-recordings' ),
		SJ: _x( 'Svalbard and Jan Mayen', 'text', 'nelio-session-recordings' ),
		SE: _x( 'Sweden', 'text', 'nelio-session-recordings' ),
		CH: _x( 'Switzerland', 'text', 'nelio-session-recordings' ),
		SY: _x( 'Syrian Arab Republic', 'text', 'nelio-session-recordings' ),
		TW: _x( 'Taiwan', 'text', 'nelio-session-recordings' ),
		TJ: _x( 'Tajikistan', 'text', 'nelio-session-recordings' ),
		TZ: _x(
			'Tanzania, United Republic of',
			'text',
			'nelio-session-recordings'
		),
		TH: _x( 'Thailand', 'text', 'nelio-session-recordings' ),
		TL: _x( 'Timor-Leste', 'text', 'nelio-session-recordings' ),
		TG: _x( 'Togo', 'text', 'nelio-session-recordings' ),
		TK: _x( 'Tokelau', 'text', 'nelio-session-recordings' ),
		TO: _x( 'Tonga', 'text', 'nelio-session-recordings' ),
		TT: _x( 'Trinidad and Tobago', 'text', 'nelio-session-recordings' ),
		TN: _x( 'Tunisia', 'text', 'nelio-session-recordings' ),
		TR: _x( 'Turkey', 'text', 'nelio-session-recordings' ),
		TM: _x( 'Turkmenistan', 'text', 'nelio-session-recordings' ),
		TC: _x(
			'Turks and Caicos Islands',
			'text',
			'nelio-session-recordings'
		),
		TV: _x( 'Tuvalu', 'text', 'nelio-session-recordings' ),
		UG: _x( 'Uganda', 'text', 'nelio-session-recordings' ),
		UA: _x( 'Ukraine', 'text', 'nelio-session-recordings' ),
		AE: _x( 'United Arab Emirates', 'text', 'nelio-session-recordings' ),
		GB: _x( 'United Kingdom', 'text', 'nelio-session-recordings' ),
		US: _x(
			'United States of America',
			'text',
			'nelio-session-recordings'
		),
		UM: _x(
			'United States Minor Outlying Islands',
			'text',
			'nelio-session-recordings'
		),
		UY: _x( 'Uruguay', 'text', 'nelio-session-recordings' ),
		UZ: _x( 'Uzbekistan', 'text', 'nelio-session-recordings' ),
		VU: _x( 'Vanuatu', 'text', 'nelio-session-recordings' ),
		VE: _x( 'Venezuela', 'text', 'nelio-session-recordings' ),
		VN: _x( 'Vietnam', 'text', 'nelio-session-recordings' ),
		VG: _x( 'Virgin Islands, British', 'text', 'nelio-session-recordings' ),
		VI: _x( 'Virgin Islands, U.S.', 'text', 'nelio-session-recordings' ),
		WF: _x( 'Wallis and Futuna', 'text', 'nelio-session-recordings' ),
		EH: _x( 'Western Sahara', 'text', 'nelio-session-recordings' ),
		YE: _x( 'Yemen', 'text', 'nelio-session-recordings' ),
		ZM: _x( 'Zambia', 'text', 'nelio-session-recordings' ),
		ZW: _x( 'Zimbabwe', 'text', 'nelio-session-recordings' ),
	} );

export function getCountryName(
	countryCode: string,
	defaultName?: string
): string {
	const fallback =
		defaultName ?? _x( 'Unknown', 'text', 'nelio-session-recordings' );
	return worldCountries[ countryCode ] ?? fallback;
} //end getCountryName()
